### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by SevorisDoe** [TheCedarPrince/NoteMate#1]
So that we can keep a track of this: 

Improving documentation for this, so that the internal methods and structural representations become clearer. That should allow easier understanding of the current capabilities and workflow that is designed into NoteMate. Future options that could be empowered by things like this are alternative static site generators, or translating semantic information in a different notes structures to the common notes format underpinning the implementation.

**Comment by TheCedarPrince** [comment]
@SevorisDoe , I think the other issues open cover this issue pretty well so I am now going to close it in lieu of the other issues.
